### ISSUE TITLE
Fix no TextView de anotações

### ISSUE THREAD

**Issue by davirss** [rafaelcoutinho/cowbird#15]
Foi reportado um problema em que o text view de anotações fica muito pequeno quando um teclado ao tentar editá-lo, dificultando a leitura.

**Comment by rafaelcoutinho** [comment]
@DaviRSSilva  dê uma olhada nesse cara https://github.com/rafaelcoutinho/cowbird/tree/EDITTEXT

**Comment by davirss** [comment]
Creio que está resolved então. Testei aqui
